### ISSUE TITLE
how  to add odometry data?

### ISSUE THREAD

**Issue by plumewind** [cartographer-project/cartographer#1464]
Hello, friends
I use turtlebot2 in ROS gazebo,I have set the lua:

  map_frame = "map",
  tracking_frame = "base_link",
  published_frame = "odom",
  odom_frame = "odom",
  provide_odom_frame = false,
  publish_frame_projected_to_2d = false,
  use_odometry = true,
  use_nav_sat = false,
  use_landmarks = false,

but , it always error:
F1119 10:05:45.271495 26453 map_by_time.h:43] Check failed: data.time > std::prev(trajectory.end())->first (621355991307850000 vs. 621355991307850000) 
[FATAL] [1542593145.271714611, 2330.794000000]: F1119 10:05:45.000000 26453 map_by_time.h:43] Check failed: data.time > std::prev(trajectory.end())->first (621355991307850000 vs. 621355991307850000)

Can someone help me? Thank you

**Comment by gaschler** [comment]
Please post the results of rosbag_validate following the issue template.

**Comment by qust001** [comment]
same to me
