### ISSUE TITLE
Failed to process package 'cartographer'

### ISSUE THREAD

**Issue by programmeDuan** [cartographer-project/cartographer#1468]
when I install cartographer , executing "catkin_make_isolated --install --use-ninja",the result :> cmake /home/dgx/catkin_ws/src/cartographer -DCMAKE_INSTALL_PREFIX=/home/dgx/catkin_ws/install_isolated -G Ninja in '/home/dgx/catkin_ws/build_isolated/cartographer/install'
-- Build type: Release
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   iostreams
--   regex
-- Found installed version of Eigen: /usr/lib/cmake/eigen3
-- Found required Ceres dependency: Eigen version 3.2.92 in /usr/include/eigen3
-- Found required Ceres dependency: glog
-- Found required Ceres dependency: gflags
-- Found Ceres version: 1.13.0 installed in: /home/dgx/catkin_ws/install_isolated with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, OpenMP]
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dgx/catkin_ws/build_isolated/cartographer/install
==> ninja -j4 -l4 in '/home/dgx/catkin_ws/build_isolated/cartographer/install'
[4/334] Running C++ protocol buffer co...aph/optimization_problem_options.proto
FAILED: cd /home/dgx/catkin_ws/build_isolated/cartographer/install && /usr/bin/protoc --cpp_out /home/dgx/catkin_ws/build_isolated/cartographer/install -I /home/dgx/catkin_ws/src/cartographer /home/dgx/catkin_ws/src/cartographer/cartographer/mapping/proto/pose_graph/optimization_problem_options.proto
cartographer/mapping/proto/pose_graph/optimization_problem_options.proto:15:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
[4/334] Running C++ protocol buffer co...relative_scan_matcher_options_3d.proto
FAILED: cd /home/dgx/catkin_ws/build_isolated/cartographer/install && /usr/bin/protoc --cpp_out /home/dgx/catkin_ws/build_isolated/cartographer/install -I /home/dgx/catkin_ws/src/cartographer /home/dgx/catkin_ws/src/cartographer/cartographer/mapping/proto/scan_matching/fast_correlative_scan_matcher_options_3d.proto
cartographer/mapping/proto/scan_matching/fast_correlative_scan_matcher_options_3d.proto:15:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
[4/334] Running C++ protocol buffer co...ping/proto/3d/submaps_options_3d.proto
FAILED: cd /home/dgx/catkin_ws/build_isolated/cartographer/install && /usr/bin/protoc --cpp_out /home/dgx/catkin_ws/build_isolated/cartographer/install -I /home/dgx/catkin_ws/src/cartographer /home/dgx/catkin_ws/src/cartographer/cartographer/mapping/proto/3d/submaps_options_3d.proto
cartographer/mapping/proto/3d/submaps_options_3d.proto:15:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
[4/334] cd /home/dgx/catkin_ws/build_i...d/cartographer/install/AllFiles.cmake"
ninja: build stopped: subcommand failed.
<== Failed to process package 'cartographer': 
  Command '['/home/dgx/catkin_ws/install_isolated/env.sh', 'ninja', '-j4', '-l4']' returned non-zero exit status 1

Reproduce this error by running:
==> cd /home/dgx/catkin_ws/build_isolated/cartographer && /home/dgx/catkin_ws/install_isolated/env.sh ninja -j4 -l4

Command failed, exiting.

I wantto know how to solve the problem?

**Comment by sebastianklose** [comment]
Seems you have an outdated version protocol buffers. Can you check if your installed version is compatible with what we expect. Or better yet: install the one we expect as outlined in our [docs](https://google-cartographer.readthedocs.io/en/latest/#getting-started-without-ros)?
