### ISSUE TITLE
multi resolution search?

### ISSUE THREAD

**Issue by vesor** [cartographer-project/cartographer#1486]
I am running 2d slam without IMU, on drivepx2. (arm64 cpu)
when enable use_online_correlative_scan_matching, it runs very slow.
(The speed is OK when use sample 2d bag which has imu data)

I have a look at code in real_time_correlative_scan_matcher_2d.cc, it seems the multi resolution search is not implemented. Only "2d slices" method implemented?
Also the paper mentioned the GPU implementation, any plan to implement that? Since drivepx2 has a relative fast GPU.

Thanks

**Comment by gaschler** [comment]
Cartographer currently does not use GPUs.
Hope this helps.
