### ISSUE TITLE
Know when localization trajectory matches reference trajectory?

### ISSUE THREAD

**Issue by damienrg** [cartographer-project/cartographer#1503]
I am trying to know when a localization trajectory matches with the reference trajectory.
I thought that it could be achieved by using the global slam result callback provided by #1143.

I did not find any usage of this callback and I thought that the arguments of the callback should
contains inter submap constraints (the same as the one contained in the pose graph) but after
printing values, they are not related.

Could you please answer the following questions:
 1. could you explain the differences?
 2. should I only look only for inter submap constraints of the pose graph?

**Comment by gsh89** [comment]
@damienrg Were you able to solve this ?
