### ISSUE TITLE
Setting value for submap resolutions

### ISSUE THREAD

**Issue by kllysin** [cartographer-project/cartographer#1517]
Hi!

I am new to this so apologies in advance if the question is too simple. I am trying to perform pure localization. I want to set the submap resolution parameter. I have set the lua and urdf files. 
1. Should I be adding the submap resplution to the lua file inside options? 
2. What is the default value if not set? Does anyone have a sample file? 
3. How do I check the resolution for a .pbstream file already generated.

Thanks in advance!

**Comment by MichaelGrupp** [comment]
>     1. Should I be adding the submap resplution to the lua file inside options?

Yes, you can override `TRAJECTORY_BUILDER_2D.submaps.grid_options_2d.resolution = <your resolution>`
 
>     2. What is the default value if not set? Does anyone have a sample file?

If you inherit the base config (as it's done in all examples), the default value is [this one](https://github.com/googlecartographer/cartographer/blob/master/configuration_files/trajectory_builder_2d.lua#L68), unless it was overriden by another value.

A pull request for a tool that simplifies checking the final configuration is here: #1508

>     3. How do I check the resolution for a .pbstream file already generated.

There's the possibility to run `cartographer_pbstream info <your pbstream file>`. But this doesn't print all the options at the moment. A pull request to save all map builder options is here: #
