### ISSUE TITLE
Get current pose when performing Pure Localization

### ISSUE THREAD

**Issue by hzhen95** [cartographer-project/cartographer#1524]
Hi i am a newbie to cartographer

1) i build a map with cartographer, saved it
2) i perform localization on the map in 1
3) i want to get the current pose of my robot on the map, i want to know where is my robot in the map now.

May i ask how can i get the current pose i want according to the map in 1? I tried to echo on the /move_base_simple/goal topic that is published by rviz, but i found that this topic is empty.

Best Regards

**Comment by Korbinian-S** [comment]
Hi hzhen95,

/move_base_simple/goal is part of [move_base](http://wiki.ros.org/move_base) and used to command the robot. 

cartographer_node publishes the current robot pose on  /tf. rviz is great to visualize transformations.
The corresponding frame ids are defined by the *_frame parameters in your lua configuration file. Please make sure that "pose_publish_period_sec" has a value different from 0.
[Here]( https://google-cartographer-ros.readthedocs.io/en/latest/configuration.html), you can find a more detailed description of all parameters.

Best Regards,
Korbinian
