### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by TuskAW** [cartographer-project/cartographer#1543]
Hello Everybody. I hope this is the right place to ask my question since I am not logging an issue. I am new to Cartographer, and after running the examples, I'd like to ask if there is any documentation that explains the details of what's being displayed on rviz. Thanks.

**Comment by MichaelGrupp** [comment]
Documentation for Cartographer ROS is here: https://google-cartographer-ros.readthedocs.io/en/latest/

If this doesn't help, you can post a screenshot and mark what's unclear to you.
