### ISSUE TITLE
Question: what's the difference between node and submap?

### ISSUE THREAD

**Issue by kings-landing** [cartographer-project/cartographer#1565]
According to
https://github.com/googlecartographer/cartographer/blob/master/cartographer/mapping/internal/global_trajectory_builder.cc#L68
```
    if (matching_result->insertion_result != nullptr) {
      kLocalSlamInsertionResults->Increment();
      auto node_id = pose_graph_->AddNode(
          matching_result->insertion_result->constant_data, trajectory_id_,
          matching_result->insertion_result->insertion_submaps);
```
Looks like every successful insert to submap becomes node? Isn't this making pose graph optimization problem too big?

**Comment by gaschler** [comment]
In most cases, every laser scan rotation becomes one node.
If there are multiple lidars, most people set the parameters that one rotation time span goes into one node.
The data inside a node is a (filtered) point cloud.

A submap is a grid structure (2D or 3D) of occupancy values.
It is built over 20-200 nodes or laser rotations.

> Looks like every successful insert to submap becomes node? Isn't this making pose graph optimization problem too big?

The pose graph is big, but optimization is not much effort for hundreds of submaps. Its structure is mostly a trajectory with sparse loop closure constraints.

**Comment by JD-ETH** [comment]
@gaschler Are you sure every successful scan becomes one node? I have been running cartographer with Ouster at 10 Hz, but the resulting trajectory in protobuf-stream file only has 2 nodes every second. Is there subsampling happening somewhere?

**Comment by kings-landing** [comment]
@gaschler Thanks a lot for your answer!
I have a follow-up question. In pose graph optimization, it looks like node poses get adjusted / refined, but submap probability grids are not re-generated according to their internal nodes' pose adjustment. Why is it?

**Comment by gaschler** [comment]
> submap probability grids are not re-generated according to their internal nodes' pose adjustment

Correct, submaps are only moved during optimization, but their probability grid is not changed (or distorted).

> Why is it?

Recomputing the grid in a submap is quite an effort, so it would make optimization orders of magnitude slower. I'm not aware of such kind of experiment in Cartographer.

That aside, if drift is high compared to the size of a submap, you can choose smaller submap sizes.

**Comment by ojura** [comment]
@gaschler ironically, you can actually increase the drift that way, because local slam has less features to work with.

Btw, if you allow the optimiser to optimise all trajectory nodes, you can sometimes end up with the following:
![image](https://user-images.githubusercontent.com/9062353/57531356-87315c80-7339-11e9-82bf-9440b25872b2.png)

The constraints pull in their corresponding trajectory nodes a bit stronger than the rest of the nodes in that submap. Yes, the answer might be a higher constraint builder sampling ratio, but that can end up being quite computationally expensive with larger submaps and finer resolutions.

Maybe we could optimise just the submap poses instead of using intra constraints to tie nodes to submaps?

**Comment by kings-landing** [comment]
@gaschler Thanks a lot for your answer!
@ojura you asked my question :) 
If submap is not recomputed, why not only optimize submap poses?

**Comment by ojura** [comment]
Yes, I phrased it a bit different :) It's not straightforward, though - you would have to move the nodes with submaps, and choose a way to assign each node to a submap (perhaps assign it to the older submap in the active submap pair). We would have to avoid sudden jumps between nodes which belong to adjacent submaps, and probably have to smooth the node poses according to the submaps they belong to.
