### ISSUE TITLE
Submap of outdoor scenes

### ISSUE THREAD

**Issue by Yuhaizhen** [cartographer-project/cartographer#1567]
The Submap is not continuous and the trajectory is not accurate enough when the cartographer 3D is run in real time at a speed of 5 km/h In the outdoor scene。
![2019-04-10 11-05-39屏幕截图](https://user-images.githubusercontent.com/41358582/56040399-e7e46e00-5d68-11e9-9123-00ad4652bc57.png)
![2019-04-10 11-07-41屏幕截图](https://user-images.githubusercontent.com/41358582/56040434-fc286b00-5d68-11e9-8e8e-c5ce21a58ca5.png)
![2019-04-10 11-07-45屏幕截图](https://user-images.githubusercontent.com/41358582/56040436-fcc10180-5d68-11e9-9562-091c0117888c.png)
![2019-04-10 11-07-55屏幕截图](https://user-images.githubusercontent.com/41358582/56040439-fcc10180-5d68-11e9-99d0-325aeb48c2ac.png)
![2019-04-10 11-08-12屏幕截图](https://user-images.githubusercontent.com/41358582/56040446-00ed1f00-5d69-11e9-9f15-cff6897508cd.png)
![2019-04-10 11-09-03屏幕截图](https://user-images.githubusercontent.com/41358582/56040448-02b6e280-5d69-11e9-8125-d226b27a1626.png)
![2019-04-10 11-09-16屏幕截图](https://user-images.githubusercontent.com/41358582/56040449-02b6e280-5d69-11e9-8a09-a3f08986eb83.png)
![2019-04-10 11-09-32屏幕截图](https://user-images.githubusercontent.com/41358582/56040450-034f7900-5d69-11e9-854f-468fdd941a48.png)
![2019-04-10 11-09-48屏幕截图](https://user-images.githubusercontent.com/41358582/56040451-034f7900-5d69-11e9-919d-3346a98fc9e3.png)
![2019-04-10 11-10-04屏幕截图](https://user-images.githubusercontent.com/41358582/56040453-03e80f80-5d69-11e9-8f30-eeec9acbae67.png)
![2019-04-10 11-10-34屏幕截图](https://user-images.githubusercontent.com/41358582/56040457-05193c80-5d69-11e9-9f91-94e428dfbae4.png)

**Comment by gaschler** [comment]
Please follow cartographer_ros's issue template and post the text output of rosbag_validate and your lua and urdf files.

**Comment by chenxianbo** [comment]
you can watch the cpu
