### ISSUE TITLE
estimate SLAM Quality of Service (Qos) at run-time

### ISSUE THREAD

**Issue by mojovski** [cartographer-project/cartographer#1571]
I would like to estimate the quality of the SLAM solution provided by cartographer.
It could be cor example some metric, indicating that there is 99% no better solution obtainable using global localization/ loop closing.

Maybe using one of the callbacks?
1) local slam result: https://github.com/googlecartographer/cartographer/blob/5b44305ea30e6af0d1b1edb50e758881f3330c07/cartographer/mapping/internal/global_trajectory_builder.cc#L78
2) global slam result  https://github.com/googlecartographer/cartographer/blob/601fc3c7d068af8fd6c513fd693ff282a1669fa1/cartographer/cloud/internal/map_builder_server.cc#L117 

Thanks!

**Comment by MichaelGrupp** [comment]
A similar question was answered here: https://github.com/cartographer-project/cartographer_ros/issues/1258
