### ISSUE TITLE
Typo in RangeDataSorter (tsdf_range_data_inserter_2d.cc)

### ISSUE THREAD

**Issue by pHaeusler** [cartographer-project/cartographer#1608]
There is a typo in `RangeDataSorter`

https://github.com/googlecartographer/cartographer/blob/bcd5486025df4f601c3977c44a5e00e9c80b4975/cartographer/mapping/2d/tsdf_range_data_inserter_2d.cc#L75-L76

It should read:

`const Eigen::Vector2f delta_rhs = (rhs.position.head<2>() - origin_).normalized();`

This is used later in `EstimateNormals` with the comment
> // Assumes the angles in the range data returns are sorted with respect to
> // the orientation of the vector from 'origin' to 'return'.

**Comment by kdaun** [comment]
You are right, thanks for the issue. Feel free to create a small PR fixing it.
