### ISSUE TITLE
So which optimization algorithm uses Cartographer /Ceres for scan matching anyway?

### ISSUE THREAD

**Issue by Marty146** [cartographer-project/cartographer#1619]
Hello,

So I was wondering what kind of scan matching method does cartographer use? I mean it is not ICP but a 6D optimzation of some sorts but how is that thing called. Where can I find references on it?

Thanks in advance

**Comment by kdaun** [comment]
Cartographer performs scan-to-map matching, it has separate pipelines for performing 2D and 3D SLAM.
In 2D the scan matching solves a 3DOF (x, y, yaw) optimization problem. As for map back-ends, 2D Occupancy Grids and 2D TSDFs are supported. Furthermore, an efficient branch-and-bound based scan-to-map matching approach is applied to find loop closures. A detailed description of the 2D approach is provided in [Real-Time Loop Closure in 2D LIDAR SLAM by Hess et al.](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/45466.pdf)
The 3D the pipeline is mostly similar, however, only occupancy grids are supported and the optimization problem is extended to solve for 6DOF (x, y, z, roll, pitch, yaw).
