### ISSUE TITLE
how and when cartographer compile protobuf files?

### ISSUE THREAD

**Issue by yuzy2019** [cartographer-project/cartographer#1632]
compiling cartographer needs .h files of sensor data like Imu, Odometry, but there are no .h file in the source code, only .proto files. I want to know how and when are these .proto files compiled to .h files?

**Comment by MichaelGrupp** [comment]
They are included in the CMake build. In the end, the `protoc` compiler is called to build them.

https://github.com/googlecartographer/cartographer/blob/master/CMakeLists.txt#L132
