### ISSUE TITLE
Regarding evaluation of SLAM 

### ISSUE THREAD

**Issue by vanshilshah97** [cartographer-project/cartographer#1643]
For the metric evaluation of cartographer on my dataset , I am using ATE and RPE errors.
But the number of poses, when extracted from the .pbstream file are less than the number of poses present in my groundtruth.

A humble request to help in the regard of this imbalance. What would be the solution to get the correspondence between the ground truth pose and its estimated trajectory pose.

**Comment by MichaelGrupp** [comment]
The timestamps can be easily used for correspondence. This is how e.g. [my tools](https://github.com/MichaelGrupp/evo) or the TUM RGB-D benchmark do it.
