### ISSUE TITLE
Updating free space

### ISSUE THREAD

**Issue by gullermo** [cartographer-project/cartographer#1644]
Hello,

Firs of of all,thanks for your great job.
I have been working with the cartogrpher for a while, specially with the 2D SLAM that works perfectly fine.Now I am trying to get my system working for outdoors navigation. For the moment everything seems to be working fine, but I encountered a problem that I couldn't solve. 

I am not being ablo to update de free space of the map, I am using a lidar, and for example when I it detects someone it includes it within the map (which is totally correct),however when that person is gone and the space is free again, it is not removed from the map, so when the robot tries to navigate it encounters obstacles that are actually free.

Is there any parameter that could solve the problem? What am I missing?

Any comments are more than welcome!

Thanks a lot for your help! 

Regards

**Comment by shamengjun** [comment]
Theoretically, when the person is gone, catographer will update the submaps. if your robot is still, this maybe update some slowly!

**Comment by gullermo** [comment]
Yes, it does happens with the 2D SLAM, but not with 3D SLAM, so I don't know what could be causing this issue... Any ideas?

Thanks for your answer @shamengjun

**Comment by kdaun** [comment]
Take a look at https://github.com/googlecartographer/cartographer/blob/bcd5486025df4f601c3977c44a5e00e9c80b4975/configuration_files/trajectory_builder_3d.lua#L73
To keep the computation effort reasonable the free space update is by default limited to two cells.

**Comment by gullermo** [comment]
Thanks @kdaun , I will take a look at it and report the outcomes!
