### ISSUE TITLE
seek parameters to tune cartographer

### ISSUE THREAD

**Issue by Sumyer** [cartographer-project/cartographer#1666]
Hello,
I am trying to tune three parameters in trajectory_builder_2d.lua, they are  TRAJECTORY_BUILDER_2D.ceres_scan_matcher.translation_weight, TRAJECTORY_BUILDER_2D.ceres_scan_matcher.rotation_weight, TRAJECTORY_BUILDER_2D.submapsnum_range_data.

I learned that the size of the submap should be ten to thirty seconds of data. The more I trust the odometry data, the larger translation_weight should be.  And The more I trust the IMU data, the larger rotation_weight should be.  Is it right?

But I am in trouble. How to judge the accuracy of the odometry data and the imu data? Is there any parameter from cartographer to help me?

Thanks for your help!

**Comment by MichaelGrupp** [comment]
> How to judge the accuracy of the odometry data and the imu data?

This completely depends on the sensors that you are using, so you need to try what fits your setup best.
