### ISSUE TITLE
 How to?

### ISSUE THREAD

**Issue by Zumbalamambo** [cartographer-project/cartographer#1669]
How to Install? How to run? How to get started?

**Comment by marcirsch** [comment]
https://google-cartographer-ros.readthedocs.io/en/latest/compilation.html

**Comment by Zumbalamambo** [comment]
@marcirsch does it support monocular slam?

**Comment by marcirsch** [comment]
No, cartographer can only be used with ranging sensors, like LiDARs. The input of cartographer is a number of distance measurements.

**Comment by Zumbalamambo** [comment]
@marcirsh thank you
