### ISSUE TITLE
A installation error

### ISSUE THREAD

**Issue by Rich-boss** [cartographer-project/cartographer#1672]
catkin_make_isolated --install --use-ninja
.........
==> ninja -j8 -l8 in '/home/wang/workspace-all/catkin_ws2/build_isolated/cartographer_ros'
ninja: error: '/opt/ros/kinetic/lib/liborocos-kdl.so.1.3.2', needed by '/home/wang/workspace-all/catkin_ws2/devel_isolated/cartographer_ros/lib/cartographer_ros/cartographer_start_trajectory', missing and no known rule to make it
<== Failed to process package 'cartographer_ros': 
  Command '['/home/wang/workspace-all/catkin_ws2/install_isolated/env.sh', 'ninja', '-j8', '-l8']' returned non-zero exit status 1

How do i solve it?Help please!

**Comment by MichaelGrupp** [comment]
Looks like a dependency issue, you might need to check if you installed all rosdeps etc. correctly.
