### ISSUE TITLE
How well does this work in a Driving setting?

### ISSUE THREAD

**Issue by soulslicer** [cartographer-project/cartographer#1685]
This is obviously designed for indoors, but has anyone tested this algorithm in an outdoor / self driving setting.

**Comment by wohe** [comment]
Hi, I cannot share quantitative results, but if you are mostly interested whether the algorithms were tested outdoors and with cars: yes, the 3D version has been used outdoors with backpacks and cars.

Not sure why you think the algorithm is specifically designed for indoors. With the 2D version of the algorithm you are certainly right as it needs a flat floor, but the 3D version is not limited in this way.
