### ISSUE TITLE
About installation process

### ISSUE THREAD

**Issue by kay01-kwon** [cartographer-project/cartographer#1690]
Hello

I wonder if it is possible to maintain protoc version. This is because I want to use the cartographer as a navigation tool in gazebo simulation. When building the catkin_ws containing gazebo_plugin_pkg after installing cartographer, protoc version is not compatible. In case of ROS kinetic, the gazebo plug in supports 2.7.1 and in ROS melodic, the gazebo plug in supports 3.0.0, but when installing the cartographer, the pkg automatically upgrade the protoc version to 3.4.1. Is there any way to maintain the protoc version beforehand and install the cartographer?

Thank you

**Comment by kdaun** [comment]
This issue has been discussed in detail here: https://github.com/cartographer-project/cartographer_ros/issues/625
