### ISSUE TITLE
TRAJECTORY_BUILDER_2D.loop_closure_adaptive_voxel_filter.min_num_points

### ISSUE THREAD

**Issue by xbcdbc** [cartographer-project/cartographer#1698]
Why the default value of TRAJECTORY_BUILDER_2D.loop_closure_adaptive_voxel_filter.min_num_points is 200？if the raw output of lidar is 2000 per scan，set this value to 200 is resonable？

**Comment by wohe** [comment]
Adaptive voxel filtering is applied before doing scan matching. 200 is a good compromise between  running time performance and quality.

The number of points in raw output of a LIDAR is independent of this. Think about it this way: How many points would you want to use in scan matching when your LIDAR gives you 20,000 points, 200,000 points, 2 million points per scan?
