### ISSUE TITLE
Is it possible to switch between slam and self-localization mode at runtime

### ISSUE THREAD

**Issue by shaoxiang** [cartographer-project/cartographer#1707]
Thank you for the great project. I want to switch back and forth between cartographer mapping and map based positioning. Is there any way to achieve this?
The same question, mentioned here, has not yet been answered.
[cartographer_ros #1446](https://github.com/cartographer-project/cartographer_ros/issues/1446)

**Comment by MichaelGrupp** [comment]
It is possible by finishing the mapping trajectory and starting a new trajectory with the localization config. cartographer_ros has ROS services for doing that. However, some settings currently can't be changed during runtime (trajectory options can, pose graph options can't).
