### ISSUE TITLE
Dose cartographer work on 3D tof camera?

### ISSUE THREAD

**Issue by ZuumaCoder** [cartographer-project/cartographer#1741]
Hi, If I want to use 3D tof camera to sample pointcloud which is to be used in cartographer,
Is it possible?

**Comment by chopin1998** [comment]
may be "num_point_clouds"

**Comment by MichaelGrupp** [comment]
It might work, but be aware that Cartographer 3D is known to work best with LiDAR sensors with a wide field of view.

**Comment by 3473f** [comment]
Did some testing with a SICK Visionary-T camera, but the results were very underwhelming. Our 2D Lidars (Pepperl+Fuchs R2000) resulted in more consistent results inside the warehouse. This can be down to the narrow detection angle of this specific camera as mentioned above.
