### ISSUE TITLE
precomputation_grid_3d.cc

### ISSUE THREAD

**Issue by clsgg** [cartographer-project/cartographer#1747]
I have some questions about PrecomputationGrid3D. According to the [paper](https://ieeexplore.ieee.org/document/7487258) ,the precomputed grids have the same pixel structure as the original grid, and the maximum value of the box of pixels beginning there.But I think the following code does not mean this.
```
PrecomputationGrid3D PrecomputeGrid(const PrecomputationGrid3D& grid,
                                    const bool half_resolution,
                                    const Eigen::Array3i& shift) {
  PrecomputationGrid3D result(grid.resolution());
  for (auto it = PrecomputationGrid3D::Iterator(grid); !it.Done(); it.Next()) {
    for (int i = 0; i != 8; ++i) {
      // We use this value to update 8 values in the resulting grid, at
      // position (x - {0, 'shift'}, y - {0, 'shift'}, z - {0, 'shift'}).
      // If 'shift' is 2 ** (depth - 1), where depth 0 is the original grid,
      // this results in precomputation grids analogous to the 2D case.
      const Eigen::Array3i cell_index =
          it.GetCellIndex() - shift * PrecomputationGrid3D::GetOctant(i);
      auto* const cell_value = result.mutable_value(
          half_resolution ? CellIndexAtHalfResolution(cell_index) : cell_index);
      *cell_value = std::max(it.GetValue(), *cell_value);
    }
  }
  return result;
}
```
And I think it should be modified to the following code, or I understand something wrong?
```
PrecomputationGrid3D PrecomputeGrid(const PrecomputationGrid3D& grid,
                                    const bool half_resolution,
                                    const Eigen::Array3i& shift) {
  PrecomputationGrid3D result(grid.resolution());
  for (auto it = PrecomputationGrid3D::Iterator(grid); !it.Done(); it.Next()) {
    auto* const cell_value = result.mutable_value(it.GetCellIndex());
    *cell_value = 0;
    for (int i = 0; i != 8; ++i) {
      const Eigen::Array3i cell_index =
          it.GetCellIndex() - shift * PrecomputationGrid3D::GetOctant(i);
      *cell_value = std::max(grid.value(cell_index), *cell_value);
    }
  }
  return result;
}
```

**Comment by wohe** [comment]
Hi! The Cartographer paper is about the 2D case, but 3D is very similar with two key differences:

1. the data structures are sparse, and
2. there is the option `half_resolution` to reduce the result to half the resolution.

Ignoring the fact, that you remove the support for cutting the resolution in half which is important for memory consumption, I think you're indeed misunderstanding what the code needs to do:

Think about the simple test case where only a single cell in the original grid contains a value. How many cells in the result should contain some value? How many do in your proposed code?
