### ISSUE TITLE
23410 sync_posix.cc:67]           assertion failed: pthread_mutex_lock(mu) == 0

### ISSUE THREAD

**Issue by PeakDing** [cartographer-project/cartographer#1752]
thanks your perfect job, but now I occur the problem when I run cartographer_grpc_server, can you give me a little clue?

**Comment by PeakDing** [comment]
I solve the question using gRPC-1.27.0 version, because the newer version have some variables can't be copy by default constructor

**Comment by MichaelGrupp** [comment]
These newer versions haven't been tested with async_grpc yet, so this can happen. It might change in the future.
