### ISSUE TITLE
It's possible to construct a common::ThreadPool with zero workers

### ISSUE THREAD

**Issue by macmason** [cartographer-project/cartographer#1785]
It's possible to construct a ThreadPool with zero workers. If you then schedule anything, it will hang forever. 

I'm happy to follow up with a PR, but would we prefer a `CHECK_GE(num_threads, 1)` or a call to `std::max`?

**Comment by MichaelGrupp** [comment]
I would go for the `CHECK` because zero is a value that we cannot support. A PR would be good, thanks.

**Comment by macmason** [comment]
Apparently closed this by accident. Re-opening...

**Comment by wohe** [comment]
Fixed by #1800.
