### ISSUE TITLE
kPaddingPixel effect on global pose

### ISSUE THREAD

**Issue by JakeInit** [cartographer-project/cartographer#1793]
In the final map and submaps, a border is place around the edges. The value "kPaddingPixel" determines the size of that border and is default 5. If a pixel resolution of 0.05m is used, does this mean that an extra 0.25m is added around the map and submaps? In other words, is the acutal map size actually increased. I'm trying to figure out if it has any affect on the global/local pose in the map or is it just for a more visually pleasing map?

**Comment by wohe** [comment]
The `kPaddingPixel` just enlarges the computed image when visualizing (sub)maps to ensure the full data fits. It has no effect on the data used to determine any poses during SLAM as this visualization code is not used there, so global/local poses reported by SLAM are not effected.

The visualized maps are enlarged the map data structures inside Cartographer are not influenced by this.

Thus, it does of course have an effect on the origin of the (sub)maps visualized this way, so if you refer to this as local pose, it has the effect of moving the origin.

**Comment by JakeInit** [comment]
Thank you. This clear up  the question for me.
