### ISSUE TITLE
Not possible to use IMU based extrapolator

### ISSUE THREAD

**Issue by kfabian** [cartographer-project/cartographer#1803]
Hi all,
I tried to use the IMU based extrapolator. But I get a "Not implemented!" error. It looks like this error still gets thrown if you set the option to true, even so the implementation was added in the mean time. Is this the intended behavior?

https://github.com/cartographer-project/cartographer/blob/018dded2f9a0adb7e77003d05662ada251b541f5/cartographer/mapping/pose_extrapolator_interface.cc#L87-L92

Thanks

**Comment by MichaelGrupp** [comment]
@wohe @schwoere From a quick look, this looks like an unnoticed bug in PR #1732 to me because the extrapolator is implemented but it's unreachable code. Can you clarify this?

**Comment by wohe** [comment]
@kfabian @MichaelGrupp You are right, this is not the intended behavior. I sent a PR to fix it. Note though, that the IMU based extrapolator probably needs some testing/tuning to make it useful.

**Comment by schwoere** [comment]
@kfabian As indicated by @wohe, I believe the plan was to remove the `CHECK` once good parameters for the official datasets were found. Anyway, the implementation itself is complete and was tested with the 3D version of cartographer, so we can remove the `CHECK` (thanks @wohe for fixing).  Also see `TODO` in #1732 (https://github.com/cartographer-project/cartographer/pull/1732/files#diff-8d181dbe7716a2ccbf024b6eebc0c8c2ed0bfc3cbe18a2fc151dcdd3ae21195bR72) for the parameter tuning.
