### ISSUE TITLE
I have something wrong when cmake..

### ISSUE THREAD

**Issue by AdamPengG** [cartographer-project/cartographer#1810]
Hi authors of cartographer,
I have some problem when the second time installing cartographer.I have follow the [cartographer_superbuild](https://github.com/larics/cartographer_superbuild) to cmake the cartographer. 
When I cmake .. the program, the terminal showing that
```
CMake Error in cartographer/CMakeLists.txt:
  Target "cartographer" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/home/peng/carto/cartographer_superbuild/cartographer/"

  which is prefixed in the source directory. 
```
After that I can still make -j4,and run rviz launch in the terminal .
But in the Clion, there is a problem that clion can't find the cartographer header files.
And the program can't debug in it.
![Screenshot from 2021-02-20 16-50-28](https://user-images.githubusercontent.com/45864105/108646016-8c9c6e80-74ef-11eb-9243-a3373b036ef8.png)

**Comment by MichaelGrupp** [comment]
I suggest to open an issue in the "superbuild" repository instead of here, because we can't support this.
