### ISSUE TITLE
node_mian.cc use ros::AsyncSpinner instead of ::ros::spin()

### ISSUE THREAD

**Issue by PeakDing** [cartographer-project/cartographer#1811]
Hello, Google author:
I have a question ,in node_mian.cc at cartographer_ros, I use ros::AsyncSpinner instead of ::ros::spin()， my code is below
`ros::AsyncSpinner async_spinner(2);
  async_spinner.start();
  ::ros::waitForShutdown();`
The problem is sometimes the project would be crash randomly.

**Comment by MichaelGrupp** [comment]
Since we only use `ros::spin()`, there's no guarantee that an async spinner would work or support for that from our side. You need to debug this yourself if you really want to use an async spinner in your fork.

Note: this is related to cartographer_ros, not cartographer library.
