### ISSUE TITLE
External Pose update to Cartographer localization

### ISSUE THREAD

**Issue by yashmanian** [cartographer-project/cartographer#1822]
Hi,
I'm not sure if this has been answered in another issue already, but I wasn't able to find anything explicitly stating it in the issues or the documentation.
I'm trying to figure out if cartographer (in pure localization mode) has a way to:
1.  Update the localization belief using a relative feature measurement (not from the lidar. Something like an (x, y, theta) in a 2D map)
2.  Receive a global pose update from outside to help nudge its localization belief to make it more accurate over small distances.

I would appreciate some feedback on this. Thank you

**Comment by shamengjun** [comment]
Maybe add some global landmarks to some help
