### ISSUE TITLE
The x and y direction is changed in MapLimits::GetCellIndex, why must do that? And the max_ is meaning for what?

### ISSUE THREAD

**Issue by kyo055** [cartographer-project/cartographer#1830]
```
Eigen::Array2i GetCellIndex(const Eigen::Vector2f& point) const {
    // Index values are row major and the top left has Eigen::Array2i::Zero()
    // and contains (centered_max_x, centered_max_y). We need to flip and
    // rotate.
    return Eigen::Array2i(
        common::RoundToInt((max_.y() - point.y()) / resolution_ - 0.5),
        common::RoundToInt((max_.x() - point.x()) / resolution_ - 0.5));
  }
```

**Comment by sharknow** [comment]
In cartographer/mapping/2d/map_limits.h
Eigen::Array2i GetCellIndex(const Eigen::Vector2f& point) const {
// Index values are row major and the top left has Eigen::Array2i::Zero()
// and contains (centered_max_x, centered_max_y). We need to flip and
// rotate.
return Eigen::Array2i(
common::RoundToInt((max_.y() - point.y()) / resolution_ - 0.5),
common::RoundToInt((max_.x() - point.x()) / resolution_ - 0.5));
}
I think this should be:
return Eigen::Array2i(
common::RoundToInt((max_.x() - point.x()) / resolution_ - 0.5),
common::RoundToInt((max_.y() - point.y()) / resolution_ - 0.5));

I look forward to your reply!

**Comment by kyo055** [comment]
@sharknow I
 think the local coordinate is in right hand, but the grid map stores as image format which is left hand. And the x direction is always the car direction, so cartographer tries to decipt the pro
![cartogarpher_maplimits](https://github.com/cartographer-project/cartographer/assets/26664039/1e7aefaf-3abf-42f5-bdd4-f076f2a80a62)
cess as the follows.
