### ISSUE TITLE
Can cartogrpaher color the pointclouds with pictures of  Panoramic camera？

### ISSUE THREAD

**Issue by nonlinear1** [cartographer-project/cartographer#1835]
I want to get dense color pointcloud after running cartographer. So I want to color the pointcloud with the pictures of Panoramic camera.  How can I change the code of cartographer? Could someone have done this work? or Anyone can give me some suggestion. Thank you very much!
My hardware : two vlp16 lidars, a microstrain imu 3dm-gx5-25

**Comment by nonlinear1** [comment]
I have succeeding in this ideas

**Comment by ShrutheeshIR** [comment]
Hello @nonlinear1 , I am also looking to do this, could you briefly outline your steps?
