### ISSUE TITLE
Please recommend me good choices of IMU and Odometer

### ISSUE THREAD

**Issue by roboomega** [cartographer-project/cartographer#1930]
Hello,
I am using Cartgrapher on Ubuntu 20, not Cartographer_ROS
I am using MapBuilder in Cartographer directly

I am looking for a good IMU and good Odometer for this purpose

Could you please recommend me some good choices for those products?

Thank you and have a nice day

**Comment by roboomega** [comment]
Hello, this issue is solved now
Thank you

**Comment by Alex-Beh** [comment]
@roboomega would you mind to share the solution?
